### ISSUE TITLE
Search functionality after flattening

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#10]
This is a marker to keep us thinking about the way the search will work after the site has been flattened to HTML. Plans as of 8/11 are as follows:

1) Fix the attribute search for faunal species so that clicking on a link to a species (or anatomical part?) will take the user to a results page with all pages where that item is represented (this is tricky because those items do not have modules -- so all species and anatomical parts will only show up on context module pages)

2) Possibly aggregate some of the most commonly searched small-find types (coins, spindle whorls, gamepieces, fishhooks, weights, vessels, architectural fragments, etc.) so that those can also be recovered as searches when the internal free-text search functionality disappears

3) In the "freeze-drying" process, replace the internal free-text search function with a link to a Google "search this site" page, with a dummy site URL to be swapped out for the final site URL when hosting is worked out

**Comment by MikeJJohnson** [comment]
Here are the unique short descriptions.
[distinct short descriptions.txt](https://github.com/atomrab/chersark/files/5057584/distinct.short.descriptions.txt)

**Comment by atomrab** [comment]
I've attached all ~800 of these to 55 classes, which represent both the general and common types that people are likely to search for, like "coin", and some of the more unique items that will be hard to find without a free-text option. As a bonus, this has allowed me to reconcile all of those classes with the Getty AAT -- if adding these classes by matching them with the short definitions in small finds is still within scope, this would round out our LD approach. Both the class mapping and the Getty AAT mapping are now in [https://github.com/atomrab/chersark/tree/master/attribute_authority_alignment](https://github.com/atomrab/chersark/tree/master/attribute_authority_alignment).
