### ISSUE TITLE
Is there a way to delete a record from a module?

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#13]
We have a number of records that are tests, or "canceled", or otherwise not useful. Can/should we delete these, to avoid confusing future users of the database with extra list items, or should we leave them as archival elements with clear notes that they are "dead" records, not good data?

**Comment by MikeJJohnson** [comment]
Yes, we can and I think should delete these junk records.

**Comment by MikeJJohnson** [comment]
I have left those records that have paper sheets saying "cancelled", as I think that these might be interesting later (if for example these numbers are referenced in a notebook or equivalent. The test records I have removed.
