### ISSUE TITLE
Adjust decimal places in coin measurement fields

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#14]
A placeholder for a change we've discussed: currently, the decimal places for "axis" and "diameter (measured by coin specialist)" are in the wrong place -- the first is in the form .07 and the second in the form .2. The axis should be an integer from 1-12 (so the decimal place needs to move two places to the left -- here the value should be "7"), and the second should have the measurement unit added to the field name ("diameter in mm (measured by coin specialist)") and should be of the form ##.#, with one significant digit (so here the value should be "20.0", in mm). The other diameter value, inherited from the small find registry, was measured in cm and can remain the same (though it would be helpful to add "(cm)" to the diameter, length, width, and height fields).

**Comment by atomrab** [comment]
This looks good, but we still need to indicate units (mm) in diameter (measured by coin specialist) and change units from mm to cm for our general "diameter" (e.g. for [https://ica.tacc.utexas.edu/chersonesos/ark/sfi_cd/CH05SR_3175.html](https://ica.tacc.utexas.edu/chersonesos/ark/sfi_cd/CH05SR_3175.html), we have "length 2.4cm" (ok, should be diameter, but the measurement and units are correct), "diameter 0.15mm" (should be 0.15cm -- not really diameter, but at least the units should be changed, since it must actually be 1.5mm thickness), and "diameter (as measured by specialist) 24" (correct in mm, but should be noted that it's mm in the field name -- "Diameter in mm (as measured by specialist)").

**Comment by MikeJJohnson** [comment]
OK, sorted this out now - I hadn't appreciated there were two types of diameter using different units. With that example I have switched the numbers into the right fields, but in general if numbers are in the wrong place it will be hard to fix them.
