### ISSUE TITLE
Double-counting of faunal remains for some layers

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#15]
While investigating #8, I noticed that some layers from the 2004 season present double counts of faunal remains in both the summary table and the anatomical part table. In most cases, the double count appears under one heading (so instead of 4 crab fragments as presented in the database, 8 appear), but in the case of the blank rows, the values are not merged but repeated (so in the case of a missing species name for "sturgeon" with a count of 2, there are two blank rows next to each other, each with a count of 2). This suggests that it is the rows, not the counts, that are being doubled, and then merged where the labels are the same. 

I have identified this problem in all layers with faunal remains from CH04SR_337 to CH04SR_364. In the case of CH04SR_344, the behavior suggests that the summary table is reduplicated in the anatomical part table: there a row for dolphin with no anatomical part appears in the anatomical table with a count of 1, and then later a row for dolphin>vertebra with a count of 1 also appears (there is only one dolphin vertebra in the layer). See below: 

![image](https://user-images.githubusercontent.com/4740995/90811262-ebd3b900-e2e9-11ea-9808-3ec88956b48d.png)

Is it possible that the creation of the anatomical part table somehow incorporated the summary table values, which were then reflected back into the summary table, doubling the counts for that table as well? There are five pig bones total and five identified parts in that layer, though they refer to the same bones -- maybe they've been added together somehow?

Starting with CH04SR_369, the problem disappears. I'm not sure why it's only that first batch of CH04 records that are affected, but I hope this means it's easier to fix.

**Comment by MikeJJohnson** [comment]
These records were imported into ARK twice, sometime in 2014 - the duplicates have been removed
