### ISSUE TITLE
Combining some apparent synonyms in faunal tables

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#16]
Should I merge, in the raw data table for the faunal remains, some values that seem to be different terms for the same thing, used in different field seasons? I'm pretty sure that Equus asinus and Asinus domesticus refer to the same species, and I think that the "Sturgeon" value should actually be "Sturgeon-type", since I'm not confident that Russian terminology was specific to a particular sturgeon ("osetr" seems to cover a fairly wide range). Also, I don't see a difference between "Lower jaw" and "Mandible", except in terms of the year the record was made.

I can change all of these in the faunal spreadsheet, since I imagine it would have to be re-imported anyway (I hope this is something relatively easy). We lose a little bit of the legacy data, but I'm not sure that terminological inconsistency is that useful in terms of legacy, and the artificial distinction between "lower jaw" and "mandible" or "sturgeon-type" and "sturgeon" will probably just confuse people.

**Comment by atomrab** [comment]
@MikeJJohnson let me know your thoughts on this as soon as possible, so that I can make changes and finalize the faunal table if you think it's better to merge those three doubled values.

**Comment by MikeJJohnson** [comment]
I am not sure. If this is not much work then yes go ahead, although the metadata should solve this sort of confusion.

As you note the faunal remains will need to be reimported anyway.

**Comment by atomrab** [comment]
It's not much work at all. I'm mainly concerned with users who want to aggregate data and do statistical analysis, and who won't automatically grab both. I'll knock this out right away and send on. I'll leave a note in the "notes" field of the original csv, which I will also archive, that explains which values were originally "sturgeon", "Lower jaw", and "Asinus domesticus".

**Comment by atomrab** [comment]
Ugh, actually, I'd already done separate mappings for "lower jaw" and "mandible", so I'll leave those. I also see that both Donkey and ass are mapped to the same value for Equus asinus, but I'd still like to combine them into one Donkey=Equus asinus, and I'd like to do the same for sturgeon and sturgeon-type. I'll make an alternate file, in case the change creates unexpected issues for ARK, in which case we can punt the issue.

**Comment by MikeJJohnson** [comment]
Alternative file has now been uploaded
