### ISSUE TITLE
Addition of paleobotanical species summary table/chart

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#17]
This is a marker for the discussion we've had about adding the paleobotanical species count by context, as for the faunal, ornithological, ichthyological, and ceramic remains. @MikeJJohnson has a table with the breakdown by sample and context; the results are already linked to the samples by species but not by count (e.g. https://ica.tacc.utexas.edu/chersonesos/ark/smp_cd/CH05SR_123.html).

**Comment by MikeJJohnson** [comment]
The paleobotany counts have been added, and displayed in a table, the pie chart is not currently working - how important is this?

**Comment by atomrab** [comment]
Not at all -- no reason to spend time on this. The samples are too small and the variety of species too great to make these useful.

Is it possible, though, to provide summary counts by context on the context pages themselves, so that people don't have to click to each sample to see what's there? I know our pages are getting very long, but I think we're prioritizing richness of information over aesthetics at this point. If this isn't just a matter of copy-pasting the code for eg the bird remains, though, it's not critical. If it's a matter of merging samples so that there's only one set of results per context, I can do this manually if it's not possible to do it programmatically.

**Comment by MikeJJohnson** [comment]
I have added the list of species to the context page, adding the counts would be difficult. I don't think there is scope for consolidating multiple samples at this stage

**Comment by atomrab** [comment]
Yup, that makes sense. The spreadsheets and the JSON will be available for anyone who wants to put it back together down the road. Thanks for adding the species!
