### ISSUE TITLE
Can't remove erroneous C/N entries

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#19]
I mistakenly added Mainz C/N values to CH02PA_SK10 instead of CH02PA_SK8 (clicked on edit view for "Dating" box, added values, clicked "edit" button, update successful). When I realized this, I attempted to correct the error by deleting those values in the edit view and clicking the "edit" button again -- but I got the message "No errors were present and YET no query was executed", and the values reappeared.

We don't necessarily need to fix the cause in this case; I'm fine curing the symptom, if @MikeJJohnson has a way to delete those values. As I go through for the last major editing pass, though, I do need to know if I can expect this behavior in any blank field I mistakenly add data to, or if it's just a feature of the skeleton form -- so that I can plan to triple check moving forward.

**Comment by atomrab** [comment]
Corollary: this mistake happened because CH02PA_SK8 is missing from the DB for some reason (so I hit SK10 when I should have hit SK8). I just tried to add it through the skeletal remains register, but received an error message that "The value SK8 is not numeric". Could we remove the validation from the skeletal remains register so that I can add this item? Or @MikeJJohnson, could you add this on the backend manually? I haven't found other missing skeletons yet, but if there are others, it makes more sense to make it possible to add them in the register (or I can just send a list).

**Comment by atomrab** [comment]
Update: there is at least one additional CH02PA skull that didn't make it into the register in the db (CH02PA_SK1A). It would be very useful to be able to include this one, because it has isotopic results from Mainz and is one of the two possible non-locals in the group.

**Comment by atomrab** [comment]
Ok, there are quite a few mandibles I need to add that were subject to C/N and Sr analysis at Mainz -- six more, from CH06SR_911, none of them numbered in the main register. I think I'd need to name these in the form CH06SR_M1, M2, etc.; if we can turn off the validation on the skeletal remains register, would this naming form be possible, or do I have to stick with SK or SKL?

**Comment by MikeJJohnson** [comment]
M1, M2... etc naming is no problem.
I have removed the numeric requirement from the validation for skeleton items, it is still in place for other modules.
