### ISSUE TITLE
Anonymous User Login

### ISSUE THREAD

**Issue by MikeJJohnson** [atomrab/chersark#2]
Following a link from the datablog takes you to the anonymous user view, if you're not logged in as someone else, but going directly to the ARK to use as a guest forces a login; if I put in anon as user and anon as password, Chrome tells me the password has been compromised and we should reset it.

Is this a problem we need to address while we've got collaborators using the database? Having an open version that they don't need to log into is pretty helpful, but then we need a way to get them to the homepage without opening security holes.

**Comment by MikeJJohnson** [comment]
Chrome is right that "anon:anon" is not great security, we can include those credentials in the links and log in automatically, which will bypass the chrome warning.

**Comment by atomrab** [comment]
I think we just need to make sure that someone can't tunnel in to the server using those credentials.

**Comment by MikeJJohnson** [comment]
The Guest user does not pose a security risk so far as we know
