### ISSUE TITLE
Need to add new skeletal material to skeletal register but having id validation problems

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#20]
Moving from #19.

**Comment by atomrab** [comment]
> Corollary: this mistake happened because CH02PA_SK8 is missing from the DB for some reason (so I hit SK10 when I should have hit SK8). I just tried to add it through the skeletal remains register, but received an error message that "The value SK8 is not numeric". Could we remove the validation from the skeletal remains register so that I can add this item? Or @MikeJJohnson, could you add this on the backend manually? I haven't found other missing skeletons yet, but if there are others, it makes more sense to make it possible to add them in the register (or I can just send a list).

**Comment by atomrab** [comment]
> Update: there is at least one additional CH02PA skull that didn't make it into the register in the db (CH02PA_SK1A). It would be very useful to be able to include this one, because it has isotopic results from Mainz and is one of the two possible non-locals in the group.

**Comment by atomrab** [comment]
> Ok, there are quite a few mandibles I need to add that were subject to C/N and Sr analysis at Mainz -- six more, from CH06SR_911, none of them numbered in the main register. I think I'd need to name these in the form CH06SR_M1, M2, etc.; if we can turn off the validation on the skeletal remains register, would this naming form be possible, or do I have to stick with SK or SKL?

**Comment by MikeJJohnson** [comment]
No problem to use M1, M2...
The numeric restriction has been removed from the skeleton register
