### ISSUE TITLE
A couple of plant label issues (just typographic) -- easy to fix?

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#21]
https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/227 -- shouldn't have period at the end (my fault, from spreadsheet)

Other items that had periods after "sp" in the label or elsewhere in the label inherited it in the URL, which breaks the URI -- the slug shouldn't have a period (we can remove in the label, as with other items labeled "NAME sp"): https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/238, https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/220, https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/218, https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/217, https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/200, https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/175 (could just use "s_l" at the end), https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/171, https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/169, 

https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/204 should be "Cicer arietinum" (missing a T in the second term in the db -- my fault, from the spreadsheet)

https://ica.tacc.utexas.edu/chersonesos/ark/concept/attribute/212 should be "Sambucus nigra" with a space (words are run together, again my fault from the spreadsheet)

**Comment by MikeJJohnson** [comment]
I am very impressed that you have caught these - fixed now
