### ISSUE TITLE
Add sex to CH06SR_M5

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#24]
I entered M following the spreadsheet before realizing that this was a child and should be Child M?, for this record: https://ica.tacc.utexas.edu/chersonesos/ark/micro_view.php?item_key=skl_cd&skl_cd=CH06SR_M5

I was able to delete the original sex assignment in the edit mode, but when I selected a new sex and hit the "submit" button, nothing happened. There's no reason to fix whatever edit bug is present here, but @MikeJJohnson, would you mind manually adding "Child M?" to the Sex field in the skeletal remains sheet for that record?

**Comment by MikeJJohnson** [comment]
Weird Bug, I have added it in the back end
