### ISSUE TITLE
Adding specialist coin information

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#25]
I thought that all of the specialist information had already been added for the coins, but I have just come across some entries that weren't. The specialist coin information fields don't seem to come up in the edit view of small finds, whether they're coins or not. Is there a way to populate these, either by sending on spreadsheet info where it's missing, or by enabling those fields in the small-find edit forms?

**Comment by MikeJJohnson** [comment]
What are the missing fields? The quickest way would probably be to send a spreadsheet with the missing info

**Comment by atomrab** [comment]
The missing fields are the difference between the two screengrabs below (one is for a coin that's complete, the other is for a coin that for some reason wasn't recorded in detail -- I wouldn't be antsy, except that this is perhaps the latest coin in the block, so it would be better if we could provide the full record):

![image](https://user-images.githubusercontent.com/4740995/92267906-15264480-eea7-11ea-8059-0dfea9fca6fe.png)
![image](https://user-images.githubusercontent.com/4740995/92268165-8239da00-eea7-11ea-9005-99027c49e5c3.png)

**Comment by MikeJJohnson** [comment]
Ha! weird, some point in the past those fields had been made dependant on the presence of "obverse" text. This was probably a shortcut to identifying coins. However it meant that you couldn't add the text unless it was already there.

I have disabled this check, once you have entered all the details I can activate it again before the preservation.

**Comment by atomrab** [comment]
You know, I was just writing that I thought it was something like that. Ok, I'll enter details for this one and then check to make sure that there aren't any others with the same problem, and let you know when I'm done. Thanks!

**Comment by atomrab** [comment]
This has fixed most of the problems, but there are still a couple of bugs. For https://ica.tacc.utexas.edu/chersonesos/ark/micro_view.php?sfi_cd=CH06SR_3385&sf_id=3&col_id=0&sf_nav=view, somehow the weight has populated the denomination field, and the edit function won't let me clear it for some reason. What's preventing me from deleting the value and saving? It just keeps reappearing. Is it in some underlying table?

**Comment by atomrab** [comment]
In general, would it be possible to add a small-find numerical field for "thickness (g)"? And if we did so, am I able to delete existing measurements from fields like "diameter"? The problem here is that somehow the measurement of coin thickness done by the registrar always appears in the "diameter" field, while the diameter appears in the "length" field. If I had an additional "thickness" field, I could manually move that out of the diameter field for the coins, and replace it with the "length" value. If this is impossible, I guess I'll just include it in the documentation and hope the numismatists don't beat us up.

**Comment by atomrab** [comment]
In general, I can't remove existing data from a field and leave it blank. I can change the value and save that, or I can add data to an empty field and save that, but if I have a field with bad data, I can't just remove it.

**Comment by atomrab** [comment]
Ok, apart from some shifts from reverse to reference that are errors in the original datasheet (and that I can fix if I can just remove values from "reference" etc), this seems to have taken care of all the problems with the measurements and other data not appearing.

**Comment by atomrab** [comment]
Adding the specialist coin information to COINS also seems to have added it to all other small finds, where it may be causing problems with updates to information.
