### ISSUE TITLE
Add weight to edit fields for all small finds

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#26]
I have a bunch of weights for various objects that I'd like to make sure are included in the database; can we activate the "weight (grams)" field in the "find details" edit view for all small finds?

**Comment by MikeJJohnson** [comment]
OK, weight has been moved to all finds, not just coins

**Comment by atomrab** [comment]
In case this is related to #30, I have now entered all the weights that I have for small finds, so we could remove this as an editable field (though it will still need to appear in the view mode for those objects that have a value in this field).
