### ISSUE TITLE
Can we find a way to treat "no value" for axis as something other than 0?

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#28]
I know this is a numeric field, so it's taken all blank values (no data) for "Axis" in the coin sheet and translated them as "0". This is probably fine, since that's an impossible value for axis (can only be 1-12), but it's inelegant. Can we blank out or not include the field instead where the current value is 0? Only if it's easy -- otherwise don't bother.

**Comment by MikeJJohnson** [comment]
All axis numbers of 0 have been removed. They can be removed with the [x] if they get automatically added.
