### ISSUE TITLE
Can't update material for records that don't already have a material

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#29]
I was trying to update the material for a CH01 small find (it has a class, worked bone, which implies a material, but no material value was entered in the db), but when I tried to do so in the Find Details box, the Description box threw an error and no entry was recorded:

![image](https://user-images.githubusercontent.com/4740995/92312234-6bb58080-ef84-11ea-931f-390e80ac6600.png)

**Comment by atomrab** [comment]
Follow-up, trying the same with other find details entries. This is what happens when I try to submit a "Preservation" value: 

![image](https://user-images.githubusercontent.com/4740995/92312266-c3ec8280-ef84-11ea-956b-8e4027d70060.png)

**Comment by atomrab** [comment]
And the same for "Period", below. This is the most significant problem, because one of my main activities is going to be going through the small finds and assigning periods:

![image](https://user-images.githubusercontent.com/4740995/92312293-02823d00-ef85-11ea-9fd7-40a999c60705.png)

**Comment by atomrab** [comment]
Addendum: that "was not properly set for BLANK" error comes up in every field on the page. I wonder if by adding some of the additional fields back in for edits, an edit submission is now trying to submit edits for every field on the page, but getting thrown off when changes aren't found or some fields aren't missing? Maybe it's even just that "must have obverse" validation rule?

**Comment by MikeJJohnson** [comment]
related to issue #35, fixed with the same solution.
