### ISSUE TITLE
CRITICAL: Update issues in general with SF values

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#30]
This is related to #29: I've confirmed that while it is possible to remove a period value in the "Find Details" box, it's still impossible to add a new value. Logged in as myself, when I use the edit view, select a value from the pulldown menu, and click "submit", I see the following:

![image](https://user-images.githubusercontent.com/4740995/92763682-67f57580-f359-11ea-9fc2-d775d8f74596.png)

This has to be resolved before we can close out this section of the work. If it has to do with changes made to include weight for all small finds, or changes to the validation code that required a value for "obverse", let's walk those back and I can provide weights manually (I didn't need to enter any of the missing coin values -- they all appeared by themselves when the obverse rule was removed, which I assume means they were already imported, so it's just a matter of putting dummy data into the obverse field, maybe?).

**Comment by atomrab** [comment]
Confirming this behavior: in any of the defined value fields (at least for small finds), it seems to be possible to a) add a value when a value already exists and b) remove an existing value, but it is NOT possible to add a new value when some value does not already exist in that field. So I can add a new actor to the "entered by" field when there is already the value "not recorded", but if I delete that existing value, save, and then try to enter a new value, I can't. It seems pretty clear that this ARK doesn't want to add a defined value from a list to a field that has not yet been populated.

If we can't fix the bug, would it be an alternate solution to bulk-populate a select group of fields I need to manipulate (most importantly and perhaps solely "Period", since I may be able to change material by retaining an old value there until I've added a new one -- will test) with a value like "Unknown", which I'll just delete after adding the actual value?

**Comment by atomrab** [comment]
Addendum: no error comes up when adding periods to contexts that don't have them yet, so at this point the issue seems to be limited to the small finds records.

**Comment by atomrab** [comment]
Update: bug also affects "Preservation" defined value list in "Find Details" ; new values cannot be added even if old values are present.

**Comment by atomrab** [comment]
Update: interestingly, the error message is not the same for all records. While the other small finds return the 'not properly set for BLANK' message when I try to add a period value from the list, attempting to add a period to small find CH01PA_377 (which is also a coin) produces 'No errors were present and YET no query was executed'. Maybe the difference here is that some of the 01 finds had no values entered at all under the "Find Details" set, while the 04-06 coins had material and preservation values, but not periods?

**Comment by atomrab** [comment]
Update: some of the defined values for coins (mint, issuing authority, denomination) can be updated without problems, even when material, preservation, and period cannot.

**Comment by MikeJJohnson** [comment]
I think got it. I had added a new form with the same id as an existing one, which was causing all sorts of havoc. I have renamed the form and all seems more stable.
