### ISSUE TITLE
Update on dates

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#31]
The new ISO8601 date fields work, but none of them can be left blank (this automatically replaces the value with 0 rather than with "no data"), so we (or rather I) will have to make sure that a single start or end date is just repeated as both earliest and latest start/end.

I typed in dates with leading zeroes, but these don't appear in the "view" display. To be consistent with ISO8601 format, we will need to ensure that the leading zero is added to any years that don't have four digits in the serialization (I don't care about the display, but this will be important for the JSON).

**Comment by MikeJJohnson** [comment]
The leading 0's are now added on the serialisation. It should be possible to delete the years, but they will be replaced with 0's if another field is updated.

I understand that is a frustrating bug.
