### ISSUE TITLE
CRITICAL: Can't update quantitative values for small finds

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#32]
The measurement section for the small finds now always includes the coin-specific data, which is confusing but ultimately not a catastrophe (see #25). It would be better if values like "Axis" and "Diameter (measured by coin specialist)" only appeared in coin records, but I will survive if not.

More problematic is the fact that it is no longer possible to update the measurements of any small finds. The measurement fields can be opened in edit view, and values can be added; the "submit" button produces the message "Update successful", but no values are saved and all values still appear as 0 if they were not present to begin with. 

I will definitely need to add these values before the final export takes place, so this is a critical issue. I wonder if it's not related to either my request to drop the coin validation so that we could see coins with no obverse value, or to my request to add the weight field to all small finds records. If we can dodge the problem solved in #25 by adding "Obverse not preserved" to all the missing obverse value fields, is it smarter to roll back this change and see if it solves the problem?

**Comment by atomrab** [comment]
Update -- figured out what was wrong. As long as one hits "save" after each value, the value is preserved. I have noticed this behavior in other sections as well: trying to update more than one entry, even in the same "save" section, will result in no data being recorded.

**Comment by MikeJJohnson** [comment]
Hi Adam, Glad you figured it out. There are a lot of rough edges on the
version of ARK that we are using here - one of the reasons we are doing
this archive project. With issues like this, our best workaround may be to
insert it into the back end, or use one of the upload tools.

Looking forward to seeing you later.

MJ

Michael Johnson MSc
Partner | Digital Archaeologist

L - P : Archaeology

Mob: 07999 760 818
Tel: 01244 313100
33 Lower Bridge Street, Chester, CH1 1RS

www.lparchaeology.com <http://WWW.LPARCHAEOLOGY.COM>
cIfA Registered Archaeological Organisation
