### ISSUE TITLE
Add coin fields to SF 923

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#34]
This was a coin ([https://ica.tacc.utexas.edu/chersonesos/ark/sfi_cd/CH01PA_923](https://ica.tacc.utexas.edu/chersonesos/ark/sfi_cd/CH01PA_923)) that I think was missed as a result of a data entry error in the master list of coins produced by the numismatic specialist. I've added denomination, issuing authority, and mint, but I need fields to put in the rest of the numismatic data (most of it is currently in the description field). Could we either make these fields available for this coin or add the data manually?

**Comment by atomrab** [comment]
Oops, also this one is in the same boat (mis-listed as 1135 in the register): [https://ica.tacc.utexas.edu/chersonesos/ark/sfi_cd/CH01PA_1195.html](https://ica.tacc.utexas.edu/chersonesos/ark/sfi_cd/CH01PA_1195.html). Less important, because this one is unidentified.

**Comment by MikeJJohnson** [comment]
Coin Diameter added to both of these to reveal the coin fields
