### ISSUE TITLE
Can't make fields that have information blank (and all blank numerical fields are autofilled with zero on update)

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#35]
I think that related issues have already come up (#13, #19), but it's not possible to clear a text field that previously had information in it. It can be edited -- and it can be blanked out by adding a space -- but I assume this means that the field will appear with a blank in the json export, which is presumably bad practice. The same is true for the blank numerical fields that turn into zeros (cf #28), which aren't the same as no data.

I am not very bothered by this in the interface, but we should try to keep this sort of bad data out of the json export.

**Comment by MikeJJohnson** [comment]
I can remove all the blank texts before we finish, for numbers and attributes it is possible to removed these with the little grey [x]. The numbers will be autofilled if you save any changes - which is frustrating, but it is possible to work around.
![Screenshot 2020-09-18 at 16 21 59](https://user-images.githubusercontent.com/14109538/93615600-839cf380-f9cb-11ea-9f01-38d2840e8317.png)
![Screenshot 2020-09-18 at 16 22 10](https://user-images.githubusercontent.com/14109538/93615607-84ce2080-f9cb-11ea-8ae6-f737075a0c32.png)
