### ISSUE TITLE
HTML export issue: links for the layers above and below in the matrix are broken

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#45]
These links also lead to a micro_view.html file in the export, even though the clean URL seems to be encoded for those links in the dynamic database. We DEFINITELY need to ensure that these links work properly in the static version, especially if there are barriers to search functions that take you directly to a specific layer. Imagine seeing that your layer is over layer X, and only being able to navigate to layer X by going back to the full list of contexts and paging through 25 items at a time, for 1000 contexts.

**Comment by atomrab** [comment]
Is this because the path in the dynamic database doesn't end in .html, as an html page, but just with the context code number? Or is this irrelevant? There's no php call visible in the URL.

**Comment by MikeJJohnson** [comment]
I this is because this was an older version that was exported, will be fixed in any future export.
