### ISSUE TITLE
HTML export issue: all the Wordpress links have disappeared

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#48]
Can we get these back? I can live with the lost of the "Search Linked Wordpress for this entry" link in record view, if this is an irremediable php issue, but I would like to retain the hard-coded searches for individual module items if at all possible.

**Comment by MikeJJohnson** [comment]
The search linked Wordpress will be back, this export is from before that was implemented. The search box needs looking at - I'll see what I can do.
