### ISSUE TITLE
Missing Birds

### ISSUE THREAD

**Issue by MikeJJohnson** [atomrab/chersark#5]
I've discovered, going back over the bird records (because I kept seeing contexts where the archaeozoologist identified birds, but there were no bird specialist records), that I missed a bunch of layers that for some reason the specialist included in her 2005 report but omitted from the more holistic 2005-2006 report. If I go through those and add them to the csv file I sent you before, how much of a pain in the ass would it be to merge them? And on a related note, how much of a pain in the ass would it be to merge a table set up like the faunal db, with one row per combination of species, layer, and anatomical part? The ornithologist broke it all down by part, too, and that might be kind of cool to look at (but again, not if it's a hassle).

**Comment by MikeJJohnson** [comment]
The Animal Bones turned out to be pretty easy so we can certainly do that. We would need to think about mappings for the parts, or are they the same? A phalange is a phalange but are beaks mandibles?

**Comment by MikeJJohnson** [comment]
had been wondering why we had quite so many European jay remains, and when I just looked back at the bird spreadsheet to check format, I realized why: all of the counts have been associated with a species column one to the right of the original proper column. So now it looks like we have lots of jays (Garrulus glandarius) and lots of European shag (Phalacrocrorax aristotelis), but IN FACT all those numbers are associated with Gallus gallus (the chicken) and Otis tard (the great bustard), which makes a hell of a lot more sense (you eat chickens and bustards). We definitely need to fix this; please let me know if I can help in any way to do so.

**Comment by MikeJJohnson** [comment]
Right! I think in this case we will need to pull all the birds out and reimport as it will be difficult to piece it together inside the database.

Are you able to send me the spreadsheet again with the correct column alignment and the missing 2005 layers?

**Comment by atomrab** [comment]
The column alignment is correct in the CSV file in the Github repo -- the misalignment must have happened in the import (because the first column of contexts was ignored, maybe?). But I will go through and add the 2005 layers.

If we can use the anatomical parts, however, would you prefer to have a spreadsheet with one row per context per species per part (so CH05SR_509, Gallus gallus, femur, 1; CH05SR_509, Otis tarda, pelvis, 2; etc.), rather than the current version with one row per context, with species indicated by column headers? I think I can do this, but it may take me a little longer. Let me know if this is the way to go.

**Comment by atomrab** [comment]
> The Animal Bones turned out to be pretty easy so we can certainly do that. We would need to think about mappings for the parts, or are they the same? A phalange is a phalange but are beaks mandibles?

We'll need to add mappings for bird parts. I will add those to the original sheet. I think we can keep using parts that are common to both birds and mammals for both.

**Comment by atomrab** [comment]
I have now provided mappings for both a few new bird species (in our ncbi_eol alignment table) and for all the anatomical parts catalogued for both birds and fish, with correspondences with the mammal parts as appropriate (in our uberon alignment table). @MikeJJohnson, I've also sent you the updated tables with species count by context and with the anatomical breakdown by species and context for the birds. Let me know if you think we could (or should) do the same with fish.

**Comment by MikeJJohnson** [comment]
The birds data is now corrected

**Comment by atomrab** [comment]
Argh, sorry, @MikeJJohnson -- the reimport replicated the column shift problem, so we're back to the crazy numbers of European jays and shags again. Can I help with this by changing the format of the table somehow?

**Comment by MikeJJohnson** [comment]
oops, that was my mistake, fixed it now
