### ISSUE TITLE
"Search Records" labels and categories need to be refined (in the dynamic db, propagating to the export)

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#50]
Some of these categories should be relabeled: "Context type" on search page should just be "Contexts", because that filter just pulls up a list of all the contexts, rather than filtering by type. "Anthro Analysis" should be "Human Remains", since the element is skeletons and skulls, not analyses. "Groups" would probably be clearer as "Context Groups" (in which case it would make sense to place it right after "Contexts").

Some of these categories should be deleted: we don't have a "Finds Photos" module (we just linked these by file names, no other metadata), so this should go, and we don't have a "Files" module, so unless this goes to a list of all the file resources we link to (it doesn't -- it just throws an error), it should go too.

One of these categories failed to export to HTML: "People" returns results in the dynamic db, but throws a missing file error in the export ("Firefox can’t find the file at /Volumes/gorgoneion/ica/sr_pub/ark_statichtml_exports/chersonesos/ark/search/key/7/2.html.").

**Comment by atomrab** [comment]
Or, for Anthro Analysis, "Skeletal Remains", which is probably better because it matches the categories in the list on the home nav page (the more we can be consistent across these areas, the better).

**Comment by MikeJJohnson** [comment]
These label changes have been made.
