### ISSUE TITLE
Add category to "Search Criteria"

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#51]
We have this pretty much covered, but it would be great if we could also add the values from "Phase" in the chronology section as a separate criteria filter. I hope this would be an easy addition.

**Comment by MikeJJohnson** [comment]
I have added the phase filter. Are the phase values linked to period, or independent?

**Comment by atomrab** [comment]
The phases are independent of the periods (this is another way that I'm thinking about exploring chronological reasoning across the datasets). I will put up our table of phases as CSV in the repo; I'm not sure what parts of this are in the ARK table of phases (just labels? dates?), so if you could export that table and put it in the repo too, we can see what's there.

**Comment by MikeJJohnson** [comment]
At the moment the Phases are just names, no other data.
[phases.txt](https://github.com/atomrab/chersark/files/5256393/phases.txt)

**Comment by atomrab** [comment]
I've put the more full explanation in the repo. I think at this point it's better to keep the phases independent in the db, without absolute dates, since those dates are likely to evolve over the next year. Once I've put in all the dating info and phased/periodized everything, it will be interesting to do another CSV export for graph analysis: in this case, contexts with period and phase with relationships, and then a separate table of small finds with period and dates by context. If we need to add phase dates at that point, we can do so in the CSV (we'd be doing this with periods, anyway).

**Comment by atomrab** [comment]
I think we can close this at this point.
