### ISSUE TITLE
Manually delete the three remaining test entries

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#52]
@MikeJJohnson, you got rid of the three BZ test entries at the beginning of the context list, but we still have three dummy entries at the end that won't resolve because their prefix is not in our db. I can't delete them because they won't resolve as records; could you kick them out manually?

![image](https://user-images.githubusercontent.com/4740995/93718877-92f37c80-fb44-11ea-9ab9-3380b9dcb26f.png)

**Comment by atomrab** [comment]
Also, can you tell me what the last item in the list of special finds is, and whether we should get rid of this too?

![image](https://user-images.githubusercontent.com/4740995/93718956-22009480-fb45-11ea-8aa2-73beda65c7a3.png)

**Comment by MikeJJohnson** [comment]
These have all been removed
