### ISSUE TITLE
Change alt-text for module search icons to remove extra plural "s"

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#53]
The magnifying glass icon provides alt-text that is a bit too Gollum for a number of items ("Search Special Findss", "Search Sampless", etc.), presumably because already-plural values were automatically pluralized again at some point. The eye icon also has an unnecessary plural ("View a Contexts"), but if this won't show up in the export, I don't care so much.

**Comment by MikeJJohnson** [comment]
I have cleaned this up
