### ISSUE TITLE
HTML export issue: "view register" button doesn't work (and probably shouldn't be there)

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#54]
I'm not sure if we intend the register view to be included in the user-facing export; it's really only useful if one is adding things, and its presence here might be due to the fact that the export used @MikeJJohnson's identity and admin role. It doesn't work, in any case, and I think it makes more sense to exclude it from the non-admin final export.

**Comment by MikeJJohnson** [comment]
subsequent exports will use the guest user not johnson_mj
