### ISSUE TITLE
HTML export issue: how do we manage number of records on display in search tab?

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#55]
The results of a search in the dynamic database default to 25, but this can be changed to set values or view all by the user. That change is carried out by a php call, however, so it doesn't transfer to the static export. Would it be possible to export pages hard-coded to 50, 100, or all values for each of the modules in the search filter, and then link to these as a pulldown list or a series of plain links? I don't think we need to allow total user customization here, and 25/50/100/all should cover 95% of use cases.

**Comment by MikeJJohnson** [comment]
Related to #47 unfortunately there isn't an easy way to do that - the rows per page will be fixed in the final export. There is a "view all" button available if the user wants to do that. 

If you think 25 is the wrong default we can change it, but I think it is a reasonable number.

**Comment by atomrab** [comment]
Got it -- but the "view all" button is currently a php call, too, and doesn't work in the export. I'd at least like to have that option working.

Whether 25 results is reasonable depends on whether it's possible to search for individual contexts and finds. Right now, because of the excavation history, the richest records are CH04 and later, but the user has to page through 300 contexts and 2000 small finds from 01-02 before getting to those, because there's no additional filter or sort mechanism for the search results (the headers are hot-linked sort ascending/descending in the dynamic version, but this is php too, so they don't work in the export). Because the page number view only goes to two pages ahead of the current view, and the highest page you can click to from the beginning is page 5, that means that it takes at least eight clicks to get to the first CH04 layers on page 19 of 47.

So I'd propose that we do one of two things: 

1) make the default 50 -- then it would only be four clicks, at least, for contexts; or

2) make it possible to jump to a results page by typing it in or selecting from a link or pulldown menu. A list of 47 links to context results pages is inelegant, but I'd prefer it as a user to having to click and click and click. At least I could jump to the middle and go back or forth. Even if we can do this, it still might make more sense to have 50 results.

Does that make sense?

**Comment by MikeJJohnson** [comment]
Makes perfect sense. I am working on the stable record jumper at the moment.

**Comment by MikeJJohnson** [comment]
There is a new stable record jumper
