### ISSUE TITLE
Edit: faunal values after (and sometimes including) Ovis/Capra alphabetically appear not to have been associated with context records

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#57]
Several of the faunal species that appear in the filter list for "Faunal Type" and show multiple record numbers don't produce any records on click. This is true for a number of species present in small numbers (e.g. "Corsac fox", "roker", "Serpenta"), but not for all ("badger" shows up) -- and also for at least one species present in numerous layers ("Domestic Pig"). I can go through the whole list and see what shows up and what doesn't, but is there any easy explanation for this apparently random distribution, like trailing white space or something?

**Comment by atomrab** [comment]
Eek, this is actually a symptom of a larger problem, which is that a bunch of data has dropped -- at least as far as I can tell -- from the faunal import at some point. And I think I have figured out why, though it's not consistent: all records following "Ovis/Capra" alphabetically, in each layer, have been omitted from the layer display and context records, although the fact that there are numbers for them in the filter suggests that they do exist somewhere in the database.

Here's the pattern, as far as I can tell: values for Ovis/Capra themselves appear up through CH05SR_678, but nothing later in the alphabet. Halfway through CH05SR_678, Ovis/Capra values themselves disappear (the total stops four rows down), and never reappear -- so all layers above CH05SR_678 don't list any species after Ovis Aries.

I am willing to bet that this has something to do with an import or display script getting derailed by the slash in Ovis/Capra. Maybe, maybe, maybe that will be an easy fix? Obviously we have to make sure that this material is displayed.

**Comment by atomrab** [comment]
I'm pretty sure this is a recent bug, by the way -- I know I've seen records for pigs fairly recently, and now they're all gone.

**Comment by MikeJJohnson** [comment]
Very good detective work here. The import had crashed before it completed (half way through CH05SR_678) I have run the end of it now.
