### ISSUE TITLE
Ensure full ARK IDs show up in JSON export

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#58]
Once we have the ARK IDs sorted out as permalinks (#37), we also need to ensure that the ids are defined in the JSON context and appear in the export with the full non-URL URI (that is, probably in a form like [South Region ID]:"87610/t66h2r/cxt_cd/CH05SR_676"). We want to make sure that the ARK and shoulder are there, rather than just the relative URL pathway "../cxt_cd/CH05SR_676.html" so that the json dump will remain transparent and citations can still be tracked down even when the static site itself is no longer online.

**Comment by MikeJJohnson** [comment]
permalinks used throughout json serialisation
