### ISSUE TITLE
Import webthumbs for site photos for lightbox display

### ISSUE THREAD

**Issue by atomrab** [atomrab/chersark#59]
Well, dang. I did find a folder full of site-photo webthumbs and the slightly larger jpg versions they came from, but they are all named according to the id conventions, not to the ark import numbers. I'm putting both folders into the Box folder where the html export was uploaded, in case these are easier to rename than the existing associated resources on the TACC server, which will also need to be downsized and converted from tif to jpg.

The webthumb numbering seems to be the same as the arkthumbs (so starting at 5573 for the site photos), but it doesn't seem to run in the same order as the sph id numbers, so I won't be able to batch rename these myself (I'd hoped I could just do a straight consecutive renaming). If reimporting and renaming from the attached external resources is the best solution, I'm all for it. And if that script is generalizable, I'm seeing from the numbering of arkthumb images that we're actually missing a lot of small-find webthumbs as well, from webthumb_3380 to webthumb_5455 (there are more arkthumbs, from 5456 to 5572, but they're related to drawings and geophotos and other things that aren't as likely to be browsed by users). These tiny thumbs are already attached to the right external resources, but not linked as lightbox-ready. If we could extract those at the same time, even better.

**Comment by atomrab** [comment]
This appears to be done -- can we close?

**Comment by MikeJJohnson** [comment]
Thumbs rebuilt from the originals
