### ISSUE TITLE
Dating Information Markup

### ISSUE THREAD

**Issue by MikeJJohnson** [atomrab/chersark#6]
Can we change "Dating Information" in the human remains module to "Isotopic analysis", which is more accurate (we'd have to adjust the ontology; I think I noted this issue there)? And can we add a field for "87Sr/86Sr" that's a numerical value expressed as a range? I suppose I can just put this in the comments, but it's more useful as a value.

**Comment by MikeJJohnson** [comment]
Do we have those numerical values? I could do an import, either way adding a new field is straightforward

**Comment by atomrab** [comment]
I've looked back over all of our documentation, and realized with some unhappiness that we never received the actual Sr results -- just the fact that most of the samples were within the range for a limestone landscape, with that numerical range specified, but some were outside it (with no additional information). So, bleah. I'm working to see if we can somehow get them, but in the meantime, just include a blank numerical field and I'll see what I can extract from our collaborator. There were only about 10 samples done, anyway, so it won't be too much trouble to put them in manually. I think we already have the C and N values, but let's make sure, please, that those have at least two decimal places, which I think is the standard (we have more like 10 from Mainz, but for the purposes of the data publication, two should be fine).

**Comment by atomrab** [comment]
Adding from email, 8/11: The 13C and 15N values are expressed in the spreadsheet with five or six significant digits, but in general they are reported only to two significant digits, and that's how they should be represented. I will copy the 86/87Sr values into a "Sr analysis notes" text field that should be added, with commentary, but if we can hold a numeric field for possible results I might obtain, it should include five significant digits.

**Comment by atomrab** [comment]
Adding from email, 8/11: We actually have two sets of C/N results, some of them for the same individuals. If it's not too much trouble, we should divide these by lab (13C (Flinders), 13C (Mainz), etc.), as we did with the 14C results. Only Flinders provided a C/N ratio, which should be to one significant digit. So: can we a) change C/N to "C/N (Flinders)", b) change the current 15N and 13C to "15N (Flinders)" and "13C (Flinders)", and c) add new fields "15N (Mainz)" and "13C (Mainz)", which I will populate myself, to the skeletal model?

**Comment by MikeJJohnson** [comment]
This has been done now
