### ISSUE TITLE
Wordpress Reverse Lookup

### ISSUE THREAD

**Issue by MikeJJohnson** [atomrab/chersark#7]
would it be possible to generate, automatically, a search URL that hits the data blog for every module ID? There isn't a lot of overlap between small find numbers and context numbers, since the small finds were in the 1000s by the 2004 season, and the contexts never got past 999 -- so it wouldn't even be necessary to search by module code, though at least preliminarily it looks like WordPress will return results for html as well as text, so you could have a search structured as e.g. https://chersonesos.la.utexas.edu/?s=%22sph%3DCH04SR_118%22.

**Comment by MikeJJohnson** [comment]
This sounds like a really cool idea and I feel like it could be implemented quickly. I will look into this.

**Comment by atomrab** [comment]
Let me know what you figure out. I do think that this could be real value added to the integration of these two pieces.

**Comment by MikeJJohnson** [comment]
I have added a link to the top of each item which does this, A lot of them lead to "No results found" but for now, I think this is good. If I get enough time there might be a way to do some automatic parsing on this - but this is something!
